// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketBooking.Repositories;

#nullable disable

namespace TicketBooking.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250112201008_Booking3")]
    partial class Booking3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketBooking.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiejscaDetailsID")
                        .HasColumnType("int");

                    b.Property<string>("VIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MiejscaDetailsID");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("TicketBooking.Entities.Koncert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KoncertImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaksymalnaIloscSiedzen")
                        .HasColumnType("int");

                    b.Property<string>("NazwaKoncertu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wykonawca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KoncertInfo");
                });

            modelBuilder.Entity("TicketBooking.Entities.MiejscaDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KoncertID")
                        .HasColumnType("int");

                    b.Property<int>("NumerMiejsca")
                        .HasColumnType("int");

                    b.Property<int>("StatusMiejsca")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KoncertID");

                    b.ToTable("MiejscaKoncertDetails");
                });

            modelBuilder.Entity("TicketBooking.Entities.Booking", b =>
                {
                    b.HasOne("TicketBooking.Entities.MiejscaDetail", "MiejscaDetails")
                        .WithMany("Bookings")
                        .HasForeignKey("MiejscaDetailsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiejscaDetails");
                });

            modelBuilder.Entity("TicketBooking.Entities.MiejscaDetail", b =>
                {
                    b.HasOne("TicketBooking.Entities.Koncert", "Koncert")
                        .WithMany()
                        .HasForeignKey("KoncertID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koncert");
                });

            modelBuilder.Entity("TicketBooking.Entities.MiejscaDetail", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
